### ISSUE TITLE
RTE not working after sorting

### ISSUE THREAD

**Issue by jbreuer** [imulus/Archetype#194]
After I discovered that you could [sort](http://our.umbraco.org/projects/backoffice-extensions/archetype/sound-off!/55264-Sort-Archetype-fieldset?p=0#comment190302) ;-) I found out that if you sort a fieldset the RTE is disabled afterwards.
![rte-sort](https://cloud.githubusercontent.com/assets/5444597/3826678/2edc95ba-1d65-11e4-9ef7-200c03fefe90.jpg)

**Comment by kgiszewski** [comment]
This will be in the next release.

**Comment by tomfulton** [comment]
Hmm, looks I'm running into this guy in Umbraco 7.3 with Archetype 1.10 - anyone else?

**Comment by kjac** [comment]
Oh no not again. I'll test in the forthcoming week (once I sober down).

🙌

**Comment by kgiszewski** [comment]
@tomfulton 7.3 is unusable for me in the present state. Plenty of breaking changes that affect me so I'd have to do a clean install (again) to test.

**Comment by kjac** [comment]
@tomfulton @kgiszewski Yeah I see the problem. It's probably got something to do with the TinyMCE upgrade in 7.3.

I think I have a fix for it, but I'll have to test it some more :) --- I'll get back to you.

**Comment by kgiszewski** [comment]
Thanks fellas, I'm on standby for upgrading to 7.3 due to this: http://issues.umbraco.org/issue/U4-7032 

I could of course use a clean install, but I'm backlogged at the moment.

**Comment by kjac** [comment]
No rush, hopefully I'll have the fix tested within this week.
