### ISSUE TITLE
.ConvertDbToString() value cannot be null

### ISSUE THREAD

**Issue by organicglenn** [imulus/Archetype#198]
I'm seeing this error in the tracelog seemingly once per field on a fieldset, after publishing some nodes, but not all.  So if I save a node with an archetype that has 5 fields, I'll see this error five times right after the 'published' tracelog entry. I only see this error on my load balanced hosted enviro, and IIS#1 is the dedicated Umbraco admin.  The 'published' and 'error' entries are all from IIS#1 tracelog.  I've confirmed the 1.4 dll is on all three enviros. 
2014-08-08 09:24:40,872 [51] ERROR Archetype.Extensions.ArchetypeHelper - [Thread 28] Value cannot be null.
Parameter name: input
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Guid.Parse(String input)
   at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)

**Comment by KirschnerMatt** [comment]
I am also getting these logs. It is just as DanDiplo describes and they usually show after stopping and starting the application in IIS. As far as I can tell, it's not hurting anything. Then again, we are having some serious issues right now with the application occasionally crashing after a publish. I'm not certain whether Archetype is the culprit or not.

**Comment by zpbd** [comment]
Seeing this issue also I believe.

Only solution I found was to delete the fieldset and add it again. Editing and re-publishing was causing this error to be logged and the field values were not updating.

I tried deleting my TEMP folder and umbraco.config and restarting the app pool.

`2015-03-30 10:28:17,175 [6] ERROR Archetype.PropertyEditors.ArchetypePropertyEditor+ArchetypePropertyValueEditor - [Thread 7] Value cannot be null.
Parameter name: input
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Guid.Parse(String input)
   at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToEditor(Property property, PropertyType propertyType, IDataTypeService dataTypeService)`

**Comment by kgiszewski** [comment]
A possible reason why this occurs: https://our.umbraco.org/projects/backoffice-extensions/archetype/sound-off!/64371-Renamed-property

**Comment by kgiszewski** [comment]
Looks like renaming a property causes issues as it never gets removed from the JSON on the document.

**Comment by kgiszewski** [comment]
Looks like this could help too: https://github.com/imulus/Archetype/pull/267

**Comment by kgiszewski** [comment]
Fixed by #269
