### ISSUE TITLE
Label Template - get text instead of value (id)

### ISSUE THREAD

**Issue by bjarnef** [imulus/Archetype#199]
Is is possible to create some helper methods, to get alternative values in the Label Template, when the properties returns id's?
E.g. when a content picker returns the id, you might want the nodename. When using lists like checkboxlist, radiobuttonlist or dropdownlist it returns the chosen id, but you might want the text instead of the value. Here I have a list of Social Media: Facebook, Twitter, Google+, LinkedIn.. but instead of displaying 14, 15, 16 or 17 it would be better to display the text.

![2014-08-10_22-34-51](https://cloud.githubusercontent.com/assets/2919859/3870451/075c1dc6-20d0-11e4-8449-543fb79d0823.png)

**Comment by milandt** [comment]
Really useful for custom label templates! Thank you for this. Just what I needed.

**Comment by kgiszewski** [comment]
Here's some sparse documentation on passing a function:

https://github.com/kgiszewski/ArchetypeManual/blob/master/02%20-%20Configuration.md#label-template

**Comment by milandt** [comment]
Thank you for that. Adding a custom JavaScript and using a function in the label template really gave me endless possibilities.

**Comment by kipusoep** [comment]
:+1:
