### ISSUE TITLE
Passing an Archetype as a macro parameter

### ISSUE THREAD

**Issue by outcome** [imulus/Archetype#215]
Hi, thanks for an awesome package :-) We use it a lot in our Umbraco systems and so far only have good things to say.
However, I do have a question/feature request. Is it possible to pass an Archetype in as a macro parameter? What I'm trying to do is use Archetype for front page widgets and I have a switch case where the code shows different HTML for different widget types (based on the alias). Then one of my widgets has a nested Archetype and I've been trying to use `JsonConvert.DeserializeObject<ArchetypeModel>` on the string that gets passed to the macro but I always get a conflict with other property editors like the uWestFest Url Picker.
Is there a way to tell the macro parameter to expect an Archetype or call the Archetype Value Converter directly?

This is the code I have:
```C#
    switch(boxAlias) {
        case "linkBox":
             var boxlinks = box.GetValue("boxLinks");
             @Umbraco.RenderMacro("Quicklinks", new {links = boxlinks})
             break;
    }
```
And then in the Quicklinks macro I have:
```C#
    var links = Model.MacroParameters["links"].ToString();

    ArchetypeModel linksModel = JsonConvert.DeserializeObject<ArchetypeModel>(links);
    foreach(ArchetypeFieldsetModel link in linksModel) {
        @link.GetValue("linkIcon")
    }
```

This gives me a null reference error coming from the `IsConverter()` method of the uWestFest Url picker. Am I doing something wrong or is this just not possible?

Thank you so much,
Sunnefa @ Outcome Software

**Comment by BenFidge** [comment]
Out of interest, how did you get archetype to work using it as a macro parameter? I tried adding a package.manifest with isParameterEditor set to ttrue, and it appears in the macro parameter type drop-down list, but selecting it doesnt do anything?

**Comment by kgiszewski** [comment]
This isn't something we're planning to support.
