### ISSUE TITLE
No way to return an Archetype listing all fieldsets including those that are disabled

### ISSUE THREAD

**Issue by joshua-stewart** [imulus/Archetype#223]
There doesn't appear to be a way top return an Archetype with all the fieldsets including those that are disabled. I have a use case where I am querying an Archetype property on one tab of the backend and displaying a new property editor based on those results as a selector on another tab (checkbox list). I need to be able to access the entire list of fieldsets regardless of their enabled/disabled status. Thanks in advance for your help.

**Comment by akeilox** [comment]
I came across the same need recently, to parse all fieldsets (including disabled). Using ArcheType 1.12.0 I used the following routine;
var fsets=Umbraco.TypedContent(iuid).GetPropertyValue<ArchetypeModel>("vacancy").Fieldsets;

Is there any method to move to a given index directly without looping through?
