### ISSUE TITLE
Multiple embedded archetypes

### ISSUE THREAD

**Issue by wroughtec** [imulus/Archetype#228]
I created an archetype with multiple embeded archetypes and it all works no problem however I noticed that on my colleagues screen (a very old 4:3 ratio screen) the inner archetype become very narrow and very difficult to edit text etc.
Would it be possible to add some responsiveness that the elements stack on smaller screens. I conceded this may be a core issue but would be great if this was possible :)

**Comment by kgiszewski** [comment]
You can add a custom stylesheet to your Archetype and/or you can even switch out the template view altogether.  Look through the Umbraco Datatype Config for your Archetype(s).
