### ISSUE TITLE
Archetype Slows Down Publish Operations Drastically

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#238]
Umbraco 7.1.8. Archetype 1.6.0. Visual Studio 2013 Update 4.

When I have an Archetype property on a content type, publishing that node is drastically slower than nodes without an Archetype property. Seems to be more of an issue when running from Visual Studio (VS) than when running from IIS. Here are the timings for a publish operation for the various environments (IIS or Visual Studio) and node types (without Archetype or with Archetype):

* IIS/Plain: <1 second
* VS/Plain: 1 second
* IIS/Archetype: 3 seconds
* VS/Archetype: 13 seconds

Seems like CPU and network activity go up during the publish operation, but CPU seems to be the likely bottleneck. Also note that I'm not using a huge amount of data on the pages with Archetypes (a dozen or so links):

![archetypes](https://cloud.githubusercontent.com/assets/5933222/5096973/9b86ddf2-6f2b-11e4-8896-72356a4c4c8f.png)

**Comment by Nicholas-Westby** [comment]
FYI, I was able to speed this up by replacing calls to dataTypeService.GetDataTypeDefinitionById with calls to ArchetypeHelper.Instance.GetDataTypeByGuid (there was already a caching facility in the code... just needed to make use of it). Note that I also had to change the access from private to internal for GetDataTypeByGuid. Publish operations are now about 10x faster:
![faster](https://cloud.githubusercontent.com/assets/5933222/5906569/7e85ddb8-a54d-11e4-80cb-25adef422a26.png)

**Comment by kgiszewski** [comment]
Well done!  Will have a look hopefully this week.

**Comment by wiske80** [comment]
Looks promising... will try it too.. thanks... Will we see a release of Archetype soon with these updates?

**Comment by kgiszewski** [comment]
Fixed with #253
