### ISSUE TITLE
Keep getting error while no archetype is chosen

### ISSUE THREAD

**Issue by sandervdpas** [imulus/Archetype#240]
My Archetype property is not required, but the properties inside my archetype are. When I want to add a row and no properties wiil be filled, it returns an error by saving the node. But when I clear the row (by clicking the minus icon), the error still occurs while it should disappear because the property isn't required.

![image](https://cloud.githubusercontent.com/assets/9931405/5165931/30c92578-73eb-11e4-8095-17101f35b99c.png)

![image](https://cloud.githubusercontent.com/assets/9931405/5165939/489999d0-73eb-11e4-9c5c-168982200c2a.png)

**Comment by markusdrake** [comment]
Thanks Tom, I'll see if I can revisit this issue in Feb. We have a site launch coming that is eating my free time.

**Comment by kgiszewski** [comment]
Duplicate with #68
