### ISSUE TITLE
Performance problems: Too many requests causing very slow loading

### ISSUE THREAD

**Issue by thesoftwarepractice** [imulus/Archetype#245]
I have an archetype list with 6 data types including one media picker and two rich text fields. The list is around 100 items long and the back-office page takes over 3 minutes to load. Initially the page was making over a 1200 requests but disabling  Deep Datatype Requests brought that down to 452 as seen below.
![performance](https://cloud.githubusercontent.com/assets/10385228/5604318/6cc563fa-93f0-11e4-8706-a1dca3dd8bf3.png)

While it has made an improvement it's still unacceptably slow, 30 seconds minimum with  caching just for the list to appear and another 1.7 minutes before the last rich text box loads and you can start editing. The publishing takes several minutes as well. 

I'm sure a lot of you have much bigger lists that a 100 items. Am I missing something?

**Comment by kgiszewski** [comment]
Hello and thank you for using Archetype.

First off, I would agree that the time you are waiting are excruciatingly long.

However, Archetype was never meant to store massive amounts of data in the way you are using it.

Loading 600 datatypes will inevitably take a long time.  Archetype is a simple wrapper that loads each datatype that is configured and knows nothing about the implementation of any of the child properties.  So if a child datatype loads external files or makes service/DB calls, it's nothing Archetype can optimize.

The best way to use Archetype is to use it sparingly per Umbraco node (list of 10 things or so).  With respect, storing so much data in a single list and expecting the UI to load 600 controls (and then run the AngularJS digest) should take a long time (unfortunately).

My suggestion would be to break up your data into a simpler design that leverages several Umbraco nodes (distribute the load) using the MNTP mixed with Archetype.

Again thank you for the feedback.

**Comment by thesoftwarepractice** [comment]
Thanks Kevin for the quick response. I guess there is nothing to do but use a different approach.
