### ISSUE TITLE
An upload or image cropper property does not seem to work in Archetype

### ISSUE THREAD

**Issue by gertdc** [imulus/Archetype#255]
I created a data type from the archetype and added an image cropper as one of the properties. In my content page I can select an image and crop it (well more or less, behaviour is not the way it should) but when I save the page, the image disappears? Is there a solution for this problem? Thanks!

Kind Regards, Gert.

**Comment by kjac** [comment]
Hi there. 
Image data types (upload and image cropper) are not supported - use a media picker instead. See #246 and #114.

**Comment by kgiszewski** [comment]
Closing as this likely won't ever be fixed.

**Comment by kjac** [comment]
Humm well I might have a fix if you want to revisit this.

**Comment by kgiszewski** [comment]
I can't remember the status of your PR, but if you got it sorted  :)

**Comment by kjac** [comment]
I've tinkered with image uploads in other datatypes since and I have a few
ideas for a revised PR. I'll cook something up when I get a chance. Just
keep this PR closed and I'll open a new one :-)

**Comment by kgiszewski** [comment]
#h5yr :)

**Comment by hsa-selectedmedia** [comment]
Hi Guys,
How do I get a specific cropUrl, now this has been fixed?
GetValue returns the Json as a string and don't know where to go from here.
Can any of you help me get passed this?

Sincerely Hasan

**Comment by kjac** [comment]
Hi @hsa-selectedmedia,

If you check the Umbraco docs and source, there's a string extension method that lets you render image crops from the persisted image cropper JSON string value.

If your image cropper value is in the variable ```crops```, you can call ```@(crops.GetCropUrl(imageCropperValue: crops, cropAlias: "Banner", useCropDimensions: true))``` to get the crop URL for the crop alias "Banner".

See https://github.com/umbraco/Umbraco-CMS/blob/2029bef6eb8b2a831f55349015dae8e5c902dfb3/src/Umbraco.Web/ImageCropperTemplateExtensions.cs#L191 for more info on the ```GetCropUrl()``` extension method.

**Comment by hsa-selectedmedia** [comment]
Hi @kjac, 

Thanks a lot for the help and feedback.
