### ISSUE TITLE
Umbraco 7.2.2 requests `en.js` language file

### ISSUE THREAD

**Issue by leekelleher** [imulus/Archetype#256]
After upgrading to Umbraco v7.2.2, I got a bunch of errors when viewing/saving any data-type that is using Archetype.

    404 (not found): /App_plugins/Archetype/langs/en.js

I'm not sure what has actually changed in v7.2.2, but my guess would be that the default culture for a back-office user has been switched from "en-GB" to generic "en".

I resolved this issue by making a copy of the `en-gb.js` and renaming it `en.js`.

Is it worth adding a default `en.js` to the Archetype distribution?

**Comment by kgiszewski** [comment]
Yep.  It was reported last night.  Trying to find time for a release.

https://our.umbraco.org/projects/backoffice-extensions/archetype/sound-off!/61678-Archetype-Shows-404-Errors-with-Umbraco-722

**Comment by leekelleher** [comment]
Thanks @kgiszewski - I can throw over a PR if that helps?

(No rush from me on a release) :+1:

**Comment by kgiszewski** [comment]
Thx, but it'll be just as easy if I do it.

**Comment by nul800sebastiaan** [comment]
Alright guys, I was finally able to repro (browser cache was tripping me up, d'oh!) and know the cause now. Please have a look at the issue: http://issues.umbraco.org/issue/U4-6307

For now the easy fix for you is to provide extra languages (en.js, dk.js, en_us.js.. yes, underscore, not dash.., etc.).

**Comment by kgiszewski** [comment]
@nul800sebastiaan Thx for tracking it down!  I'll try to get a patch out soon.

**Comment by leekelleher** [comment]
Thanks @nul800sebastiaan - makes sense!

**Comment by kgiszewski** [comment]
v1.7.1 fixed it
