### ISSUE TITLE
Feature request: Property Label Positioning

### ISSUE THREAD

**Issue by bdsoko** [imulus/Archetype#257]
I'd like to have an option on where the property label is displayed.  Currently, when displayed, it to the left of the data type.  To free up some space, especially, when nested deep, I'd like to position the label above or below the data type to free up some left-to-right space.

**Comment by kgiszewski** [comment]
FWIW, you can already do this by supplying a custom view to replace per Archetype in the advanced options.  Create an alternate view and then point to it.

**Comment by kgiszewski** [comment]
Also you can try just adding custom CSS via the advanced options as well to be inject on the page.
