### ISSUE TITLE
JavaScript Error with Color Picker

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#258]
Just noticed this error in my Chrome console on a page that has an Archetype property that contains a color picker:
![error](https://cloud.githubusercontent.com/assets/5933222/6755750/905b7a7a-cee2-11e4-813f-7c6800ed9259.png)

Note that this color picker wasn't set as required. FYI, this is probably related to a recent change to the color picker in the Umbraco core (some validation changes were made). I'm using Umbraco 7.2.2 and Archetype 1.7.1.

**Comment by kgiszewski** [comment]
Interesting.  Does this error occur as a standalone property?  We don't do a whole lot of validation stuffs and I'm curious if it's just the property editor itself.

**Comment by Nicholas-Westby** [comment]
No, I tried a standalone color picker property on a clean install of Umbraco 7.2.2 without Archetype and didn't see the error. See that part of the error message that has an hidden input field with a name of "modelValue"? That was added very recently to the color picker property editor (I think it was first seen in Umbraco 7.2.2). Maybe that'll help you track down the issue.

**Comment by kgiszewski** [comment]
You might wanna try this as well: https://our.umbraco.org/projects/backoffice-extensions/nested-content

It might play nicer.

I'm not sure when/if I'll be able to track down this bug.

**Comment by Nicholas-Westby** [comment]
Yeah, I was checking that out earlier; looks pretty neat. Might use that on my next project. FYI, though I'm getting a JavaScript error, everything still seems to work fine, so this isn't a huge problem. Just wanted to let you know.

**Comment by kasperhhk** [comment]
Looking at the scope of a normal colorpicker, and one nested in archetype, the $scope.model.validation object is missing from the archetype colorpicker.
Instead the archetype colorpicker has the value $scope.property.required set to true.

Maybe $scope.model.validation is not setup correctly, to reflect the new 7.3 changes to the validation model?

**Comment by martinabrahams** [comment]
Hi guys, this issue has been annoying me for months as well. I have made a fix for this and put in a pull request for this. 

Here's my change - https://github.com/martinabrahams/Archetype/commit/7df4d4cfcd9b2a105968e0773b1fbbce745b55e0

**Comment by kgiszewski** [comment]
Closing as the #310 addresses this.
