### ISSUE TITLE
Problems trying to deploy site using Archetype and Courier 2

### ISSUE THREAD

**Issue by Tobz91** [imulus/Archetype#263]
Hi.
I've just started using Archetype and Courier 2 and run into some problems trying to deploy my site, everything works fine local.

I get this JavaScript error loading the page in Umbraco: "TypeError: Cannot read property 'icon' of undefined at umbraco.controllers.js:4725".

I can easily reproduce this creating a brand new Data Type, an Archetype with a Content picker and a Media picker. When I deploy this to my server the choosen page is gone for the Content picker and the error message above is shown. With the Media picker I choose an image, and then when I deploy this it shows a totally different image (I've tried empty cache).

I have tried this:
* Updating Umbraco CMS to version 7.2.4
* Updating Archetype to version 1.7.3
* Deploying to 2 different servers, both get´s this problem

Any suggestions?

Thanks in advance!

**Comment by kjac** [comment]
I prefer Umport over Courier so I'm not entirely sure, but I believe you need to get the Archetype source, build the Archetype.Courier project (https://github.com/imulus/Archetype/tree/master/app/Umbraco/Archetype.Courier) and dump the output DLL in the bin folder of both the source and target environments.

**Comment by Tobz91** [comment]
Thank you, works fine!
Why this isn´t included in Archetype?

Regards Tobbe

**Comment by kgiszewski** [comment]
Apologies for the confusion.  I decided to add Courier to the distribution: https://github.com/imulus/Archetype/commit/909b87cea02c390260bfea9dcca04f2953ab733e

It'll be in all of the subsequent releases. // @leekelleher

**Comment by leekelleher** [comment]
@kgiszewski I'm not 100% sure if I'd recommend distributing the Courier resolver with the default Archetype package... as far as I recall, if a user doesn't have Courier installed, then Umbraco will YSoD when scanning the "Archetype.Courier" assembly.  But it's been a while since I tested that scenario. :weary:

**Comment by kgiszewski** [comment]
Well crap :) I'm glad I tagged you.  So maybe this won't happen after all.

**Comment by kgiszewski** [comment]
@leekelleher is correct therefore the Courier bit will not be automatically in the distribution.  I'll add the Courier DLL as an optional download.
