### ISSUE TITLE
MultiNodeTreePicker No Longer Works with Archetype

### ISSUE THREAD

**Issue by MarkoEitel** [imulus/Archetype#264]
Hello,
it seems the MultiNodeTreePicker has the same problem like the "Member Group Picker" described in Issue 261
https://github.com/imulus/Archetype/issues/261

I can select the Content but after "save and publish" there ist nothing.

My Umbraco Version is: 7.2.4.
And my Archetype Version is: 1.7.3

Greetings from Berlin
Marko

**Comment by kgiszewski** [comment]
@MarkoEitel, I'm unable to reproduce your issue.  Any chance you can verify your code is up to date?

If so, maybe you can share your config for your Archetype?

**Comment by MarkoEitel** [comment]
![archetyp_multinodepicker](https://cloud.githubusercontent.com/assets/11056836/7268800/596e0aaa-e8cd-11e4-8a00-2bd1a1282f7c.gif)

**Comment by MarkoEitel** [comment]
My configuration:
{"showAdvancedOptions":true,"startWithAddButton":false,"hideFieldsetToolbar":false,"enableMultipleFieldsets":true,"hideFieldsetControls":false,"hidePropertyLabel":false,"maxFieldsets":null,"enableCollapsing":false,"enableCloning":false,"enableDisabling":true,"enableDeepDatatypeRequests":false,"fieldsets":[{"alias":"archVeranstaltungVortrag","remove":false,"collapse":false,"labelTemplate":"","icon":"","label":"Vortrag","properties":[{"alias":"buchungVortrag","remove":false,"collapse":true,"label":"Vortrag","helpText":"","dataTypeGuid":"4ee9f7fe-9a52-4e63-bba1-5d7b017033ae","value":"0","aliasIsDirty":true},{"alias":"buchungReferent","remove":false,"collapse":true,"label":"Referent","helpText":"","dataTypeGuid":"8bde1ec3-bcd5-4660-84df-22c91e246d8b","value":"0","aliasIsDirty":true}],"aliasIsDirty":true,"$$hashKey":"2TW"}]}

**Comment by MarkoEitel** [comment]
Ups...the problem occurs only with firefox (37.0.2)
with Google Chrome 42 and Internet Explorer 11 is saving ok

**Comment by kgiszewski** [comment]
There are known issues with FF and Archetype see #202  #61. Could be related, glad you have a workaround.
