### ISSUE TITLE
Fieldsets save with a sibling's data

### ISSUE THREAD

**Issue by kgiszewski** [imulus/Archetype#268]
I can't replicate it yet (knowingly), but a few times now it would seem that saving an Archetype somehow clones another fieldset during saving and overwrites what I just did.

Umb v 7.2.4
A v1.7.3

**Comment by kgiszewski** [comment]
I can replicate this by performing a sort on a newly created fieldset that has an RTE in it. 

1. Create a fieldset with an RTE
2. Add some text, save.
3. Create another fieldset.
4. Sort it.
5. Add content.
6. Save.

The content will contain the data from the fieldset that you hit the `add` button on.

**Comment by amainguy** [comment]
I have the same issue. And it's not only on the newly created ones: it occurs when you sort then save even if the fieldsets were previously created.

My  versions are Umb 7.2.4 and Archetype 1.7.3, but I've tried to downgrade Archetype to 1.7.0 with no success.

**Comment by kgiszewski** [comment]
Looking into it right now.  I suspect it has something to do with indexes and possibly this commit: https://github.com/imulus/Archetype/commit/408c178348b7631fcc364c09f717abc61a5464a1

Will report back here if I figure something out.

**Comment by kgiszewski** [comment]
Ok, it's not the sorting code itself.  It's something to do with this: https://github.com/imulus/Archetype/blob/master/app/directives/archetypeproperty.js#L227  If I return from this function right away, the issue goes away.

Progress... :)

**Comment by kgiszewski** [comment]
While not a great solution, I'm excluding the RTE from this bit of code to avoid the issue.  Patch release to follow in a few days if I end up not changing it.
