### ISSUE TITLE
Allow User to Edit Header without Dummy Field

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#270]
I often want an Archetype fieldset to have a header entered by the user, though there is no appropriate field to display in that header. So, I end up with lots of fieldsets that look something like this:
![archetype](https://cloud.githubusercontent.com/assets/5933222/7552522/9ef239b8-f66d-11e4-8d2c-9105c2d46eea.png)

The "Label (Ignored)" is what I use a lot to allow the user to type something in the header (which, of course, allows the user to quickly preview the contents without actually expanding the fieldset).

It would be awesome if there were a built-in way to allow a user to enter something into the header without having to create a dummy field such as "Label (Ignored)". Then, the user could just click the header (or a button or whatever) and type whatever they want.

**Comment by kgiszewski** [comment]
Not a bad thought.  A simple alternative might be to write a label template function to grab the first x number of characters.  Would that be adequate? 

Making the label editable introduces additional challenges:

- max length
- reduces click target of fieldset
- do we mix editable labels with non-editable? 

Just my first thoughts.

**Comment by Nicholas-Westby** [comment]
In this instance, writing a label template function (which I've never tried... will have to look into that) may work somewhat OK for this particular example (though, a header that summarizes the text would be more effective). Though, I have more examples that don't have rich text to grab from (e.g., an image banner is just an image with no text, though a header to describe that image would be useful).

Regarding your particular challenges, here are some suggestions:
* **Max Length.** What about max length? That's not limited now, right? So why would it be limited in this scenario?
* **Fieldset Area.** That depends on how you make the header editable. You could have a button (next to add/delete/duplicate/move) that is for editing the header. That would still reduce the area of the fieldset that could be clicked and that displays the header, so maybe you could start putting the less common buttons in a "More Actions" button (basically, a sub-menu of buttons).
* **Mixed Headers.** Don't see why not. Maybe once a user edits a label, it'd just continue to show their version. Perhaps you could add an option to the fieldset designer (or whatever you call it) that has a checkbox that says "Allow user to edit header?"

**Comment by kgiszewski** [comment]
Ha. Good points. There is no current limit on length.  Any interest in tackling a PR?

**Comment by kgiszewski** [comment]
Here's some documentation on Label Templates: https://github.com/kgiszewski/ArchetypeManual/blob/master/02%20-%20Configuration.md#label-template

**Comment by Nicholas-Westby** [comment]
I'd be happy to (might be a couple weeks though). Thanks for the link.

**Comment by kgiszewski** [comment]
Btw, I'm working on 'stock' label templates in a PR: https://github.com/imulus/Archetype/pull/275

**Comment by Nicholas-Westby** [comment]
Sweet!

**Comment by kgiszewski** [comment]
Closing due to #275
