### ISSUE TITLE
Buttons Overlap with Fieldset Header

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#271]
![fieldsets](https://cloud.githubusercontent.com/assets/5933222/7574628/87301382-f7e3-11e4-957a-ef4a9867a609.png)

Notice the headers are overlapped by the buttons on the right. Perhaps you could add a margin so the header wraps before it hits the buttons. Or maybe you could float the button container right so the text wraps around the buttons.

**Comment by kgiszewski** [comment]
Hmm, pondering if we should just limit the number of characters.  Wrapped text might look weird if the fieldsets are different heights.

**Comment by Nicholas-Westby** [comment]
Not a fan of limiting the number of characters, as you can't be sure how wide the viewport will be.

The very simple solution would be to use CSS to disallow wrapping of white space, then set some transparency/gradient styles so the headers gracefully fade out before they hit the buttons (and you may need an overflow of none to prevent the fieldset header box from growing).

**Comment by kgiszewski** [comment]
Spoken like a man who's gonna send me a PR ;)

**Comment by Nicholas-Westby** [comment]
If you're acceptin', I'm requestin' :-)

**Comment by Nicholas-Westby** [comment]
After tinkering with it in the Chrome inspector for a bit, this is what I have so far:
![masking](https://cloud.githubusercontent.com/assets/5933222/7603640/bed731b8-f8eb-11e4-9599-b31c9478c972.png)

Won't work in IE as far as I know (don't think it supports CSS mask), but I'm willing to live with that if you are. Will work on a pull request later, but wanted to see if I could get it working first.

**Comment by kgiszewski** [comment]
PR merged.
