### ISSUE TITLE
Deleted fieldset influences total field validation

### ISSUE THREAD

**Issue by ane-ta** [imulus/Archetype#273]
- I have a non-mandatory archetype field.
- I create a fieldset with empty fields (one of the fields is mandatory) and try to save: getting "Property has errors" umbraco message
- I remove empty fieldset
- I try to save: getting the same "Property has errors" umbraco message
![bug-1](https://cloud.githubusercontent.com/assets/6615595/7792074/5a1e0c86-02c5-11e5-8886-f1feb75e83b8.png)
![bug-2](https://cloud.githubusercontent.com/assets/6615595/7792073/5a0ec5f0-02c5-11e5-8078-6782e96ce5b7.png)
![bug-3](https://cloud.githubusercontent.com/assets/6615595/7792072/59f0eb2a-02c5-11e5-88a5-3e404374270c.png)

**Comment by kgiszewski** [comment]
Probably related to this: https://github.com/imulus/Archetype/issues/274

I couldn't replicate your exact issue, but if you wouldn't mind trying the fix. 

Closing for now, but will reopen if this doesn't fix your issue as well.
