### ISSUE TITLE
Cannot save/publish after mandatory-validation error is shown

### ISSUE THREAD

**Issue by Tobz91** [imulus/Archetype#274]
Hi!
I'm having problems to save/publish my page after adding an element, trying to save it without choosing an image (which is mandatory) and then removing the invalid element.

To reproduce:
1. Create a brand new page
2. Adds an element with image and saves and publish the page, everything is good so far
3. Adds another element, but trying to save without choosing an image which is mandatory.
4. Removes the image I've just added and trying to save and publish again

This will still display "Property has errors" even though I don't have any errors left.

Umbraco version: 7.2.5
Archetype version: 1.7.5

Regards Tobz

**Comment by kgiszewski** [comment]
A fix for this will be released in the next patch release probably the first week of June.  If you want to fix your local copy, just look at the commit for the changes.
