### ISSUE TITLE
Icons Still Sometimes Overlap Fieldset Header Text

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#277]
Looks like my pull request didn't quite ellipse headers soon enough, as the plus icon sometimes overlaps the text:
![archetype](https://cloud.githubusercontent.com/assets/5933222/8061389/711c614c-0e7f-11e5-8351-0add234b2656.png)

I'll submit another pull request when I get a chance in a couple weeks.

**Comment by kgiszewski** [comment]
@Nicholas-Westby did we ever fix this?

**Comment by Nicholas-Westby** [comment]
I feel like the styles have changed so much that this may very have fixed itself. Haven't noticed it in a while. Feel free to close... I'll open another issue if I notice it again.

**Comment by kgiszewski** [comment]
Thanks for the feedback.
