### ISSUE TITLE
Archetype will not allow me to sort data

### ISSUE THREAD

**Issue by ifrahim** [imulus/Archetype#282]
I have created a new datatype of Archetype and added RTE in one of the fieldsets. 
When I add contents and sort order of data, it breaks...
Is this some bug in Archetype datatype? 

![archetype issue](https://cloud.githubusercontent.com/assets/5398591/9059364/3dadf82c-3aa1-11e5-9856-2b0b90327aad.JPG)

When i check browser errors, it shows: 

![error](https://cloud.githubusercontent.com/assets/5398591/9059391/70ddeaa4-3aa1-11e5-95d3-4382acde35bb.JPG)

**Comment by kgiszewski** [comment]
Can you share your Umbraco version and Archetype version?

**Comment by ifrahim** [comment]
Hi,
I am using umbraco 7.2.14 and installed Archetype 1.9 from Nuget.
It all works fine until I add item of datatype RTE

**Comment by kgiszewski** [comment]
I'm using the latest core (v7.2.8) without issue and I use Archetype extensively. If possible, please upgrade to the latest version of the core.

**Comment by ifrahim** [comment]
I have just re-installed Archetype but still no luck. I am using Nuget to install packages, could this be causing this issue?

**Comment by kgiszewski** [comment]
Nuget isn't the issue, you need to try to upgrade the Umbraco core.

**Comment by ifrahim** [comment]
Hi.
I found one of your closed issues (https://github.com/imulus/Archetype/issues/278) which is similar to what I am experiencing. 
I tried to upgrade Umbraco core as well but no luck.
I am still experiencing light blue area expanding when I try to sort fieldsets. 
I noticed that underscore.js was not installed so I did that but still no luck :(

Can you suggest something to me?

**Comment by kgiszewski** [comment]
If I recall correctly, the core upgraded underscore.js recently (it's already included in the core).

My suggestion then would be to ensure you're not using cached javascript. To clear that cache you'll need to go to your `web.config` -> `compilation` tag and set the `debug` attribute to `true`.

**Comment by ifrahim** [comment]
Thanks I did check that and compilation debug is set to true. I have attached screenshot of error.
 :(

![errors](https://cloud.githubusercontent.com/assets/5398591/9112877/6699e86e-3c49-11e5-8336-c9e56013d5ce.JPG)

**Comment by kgiszewski** [comment]
Unfortunately IHMO the error is just indicating your version of Underscore.js is out of date. Upgrading your Umbraco core should have resolved it. Please check your version to determine if that method is indeed there.

**Comment by kgiszewski** [comment]
Closed due to the numerous fixes that have come since.
