### ISSUE TITLE
Time for a UI overhaul?

### ISSUE THREAD

**Issue by kjac** [imulus/Archetype#285]
Hey! It's me again :smile: 

I've been pondering for a while if this was a good idea or not, but here goes... should the Archetype UI have a an overhaul?

I was messing around with the UI earlier and this is what came out of it. Dunno... comments?

![archetype ui 01](https://cloud.githubusercontent.com/assets/7405322/9328823/9f43105c-45ac-11e5-9d3a-735138b24338.png)

Could also go for a grid style add dialog:

![archetype ui 02](https://cloud.githubusercontent.com/assets/7405322/9328826/a1a9da2e-45ac-11e5-86e3-68b06d2c483a.png)

**Comment by kgiszewski** [comment]
I love it!

For the record, my strengths aren't UI/UX :)

I'll expect a PR ;)

**Comment by kjac** [comment]
Right-o. I'll look into it as soon as possible :)

**Comment by kgiszewski** [comment]
Out of curiosity, this is mostly markup and less/css updates right?

Reason being is I'm doing some housekeeping while adding a feature for '[min fieldsets](https://github.com/imulus/Archetype/pull/284/files)'. Just wanted to know if I can expect merge conflicts :P

**Comment by kjac** [comment]
Arrrrh...! It be all markup n' styles, matey ;) well almost, but it shouldn't cause any grand merge issues.

**Comment by kgiszewski** [comment]
No matter, let's do this!

**Comment by leekelleher** [comment]
:+1: on a UI refresh.

Just throwing an idea in the pot... why not go the whole hog and use more inspiration from the Grid? (Specifically with the sort/standby/delete icons and add button)

That's not to say make it identical to Nested Content, but in terms of consistency and UX with the back-office styles, it's worth considering :-)

**Comment by kjac** [comment]
@leekelleher Yeah well... to be honest I dislike how the buttons are hidden until you figure out you have to hover above them. I really think it's bad usability and I'm confuzzled about how it ever made it into Umbraco in the first place... :) 

That being said, if everyone else likes them there's nothing that prevents the icons from going Grid style.

**Comment by kgiszewski** [comment]
@kjac, I think they're hard to find as well.

**Comment by oooshola** [comment]
You guys have built an amazing thing here. Had an opportunity to meet Tom at uWestFest. I just have a couple of comments on the UI, one quick one, one not so quick:
1. What are your thoughts on changing the move/sort icon from the current 4-sided arrow to be the hand symbol instead? With screens these days, it currently looks identical to the add (+) icon.
2. This isn't an archetype-specific issue, but with nesting, the layout can get quite narrow. So we've implemented something called "wide mode" which essentially does this in the backoffice. Is this something you'd consider in your next update?:
```javascript
$('.form-horizontal, .form-vertical').toggleClass('form-horizontal form-vertical vert-form-fix');
```
```css
.vert-form-fix .controls-row {
    margin-left: 0 !important;
}

.vert-form-fix .control-group {
    margin-left: 15px;
}
```

**Comment by kgiszewski** [comment]
Open to about anything. Your best chance of getting a feature in the project will be with a pull request.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by oooshola** [comment]
Oh ok great. When I have some time I'll clean up/test what we've done before submitting. Thanks!

**Comment by kjac** [comment]
In my opinion the drag icon could be removed in favor of making the entire fieldset header draggable. Even though this partially means we'd be hiding the drag functionality from the user (you have to know that you can drag the header), it would improve the usability and reduce the risk of accidentally hitting the wrong icon.

**Comment by oooshola** [comment]
@kjac : I thought about that a bit...Currently there is already the expand/contract action assigned to the whole fieldset bar, which is great. Are you saying you'd somehow mix the reorder functionality with it? The risk of accidently clicking/dragging a fieldset would be high (currently, accidentally clicking/expanding a fieldset is a much more innocuous accident).

Furthermore, we generally perform an expand/contract action much more often than reordering, so even if you were to completely swap out that action just for reordering would be suboptimal--and may even initially confuse people who have already been using the fieldset bar to expand/contract. I'd hate to have to go to that little arrow way on the left every time I needed to expand a fieldset. Just my 2 cents.
