### ISSUE TITLE
Firefox won't allow valid dates to work with Date Picker

### ISSUE THREAD

**Issue by kgiszewski** [imulus/Archetype#288]
Not sure if this is Archetype specific or not yet.
<img width="989" alt="screen shot 2015-08-19 at 11 31 55 am" src="https://cloud.githubusercontent.com/assets/4653907/9360679/92715b4a-4665-11e5-8d02-0a874ffeeb08.png">

**Comment by kgiszewski** [comment]
Works as a standalone datatype but not in Archetype. Curious if Nested Content or Grid have issues (while using FF).

**Comment by kjac** [comment]
Alright so I installed FF to test this :unamused: and I bear good tidings; is it's not an Archetype issue. I get the exact same behavior with a regular date/time picker property - but only after the first save. It's like the property value does not register properly in FF. But anyway, it's not an Archetype issue so don't fret over it :wink: 

FF v40.0.2 if anyone cares.

![ff issue with date-time-picker](https://cloud.githubusercontent.com/assets/7405322/9405514/965da472-47f8-11e5-99a7-be5b422e446d.png)

**Comment by kgiszewski** [comment]
@kjac thanks for testing

**Comment by kgiszewski** [comment]
Fixed in core: http://issues.umbraco.org/issue/U4-6953
