### ISSUE TITLE
Is self-reference nesting supported?

### ISSUE THREAD

**Issue by vonbv** [imulus/Archetype#291]
I'm trying to add an Archetype type as a child to the same type, such that I have this:
* Arche1 (Archetype)
 * Name - Textstring
 * Child (Arche1)

Having that setup stops the browser from loading the content that has a property of type "Arche1". It seems like there is an endless loop going on in a script that is trying to load the structure of the content and its Archetype property. Is there a configuration I need to do or is this not supported?

**Comment by kjac** [comment]
Hey... yeah that's not gonna work. You'll want to create another Archetype configuration for nesting.

**Comment by oooshola** [comment]
I think you can have another archetype in between. i.e.
* arche1
 * arch2
  * arche1
 * name
