### ISSUE TITLE
1.11 release - 404 Error /App_Plugins/Archetype/views/archetype.html

### ISSUE THREAD

**Issue by djomen** [imulus/Archetype#299]
Just upgraded on a test site and the views folder it is looking for is not in the /App_Plugins/Archetype/ folder.

The knock on effect is i cant see my property editors for the archetype.

**Comment by kgiszewski** [comment]
Make sure to bust any Umbraco caches that may be hindering it.

Two methods:
1) Web.config edit `compilation` tag to have `debug='true'`
or
2) Update ClientdenpendencyConfig and update the version number to any unique number.

**Comment by kgiszewski** [comment]
Also, which method did you upgrade with? Nuget or Umbraco Package?

**Comment by kgiszewski** [comment]
Well crap. I see the issue. They are missing from the distro (both Nuget and Umbraco).

Fixing it now.

**Comment by djomen** [comment]
:) NuGet 

Ill give it a whirl when you have an update

**Comment by kgiszewski** [comment]
Try this: Install-Package Archetype -Version 1.11.1 in Visual Studio

**Comment by kgiszewski** [comment]
May take a few minutes to propagate on Nuget.

**Comment by kgiszewski** [comment]
Appears to be fixed now so I'm closing. Please let me know if you have additional issues. Sorry :(
