### ISSUE TITLE
ArchetypeFieldsetModel to IPublishedContent?

### ISSUE THREAD

**Issue by leekelleher** [imulus/Archetype#302]
Recently I've been exploring how to use [Ditto](https://github.com/leekelleher/umbraco-ditto) with Archetype, (for strongly-typed model mapping).  After various experiments, I ended up figuring out how to map an `ArchetypeFieldsetModel` to `IPublishedContent`, (and `ArchetypeModel` to a "content-set" aka `IEnumerable<IPublishedContent>`).

So far the code is on my ["Ditto Labs" repo](https://github.com/leekelleher/umbraco-ditto-labs/blob/develop/src/Our.Umbraco.Ditto.Archetype/Extensions/ArchetypeFieldsetModelExtensions.cs#L40), backed up with various unit-tests. I've done some testing with a "real" Umbraco website, (but still needs more testing IMHO).

My question is... would you be interested in having this in Archetype core, and exposed via a `ToPublishedContent()` extension method?

**Comment by kgiszewski** [comment]
Lee thats sounds amazing and would definitely welcome it in the core.
I haven't looked at the repo yet but I 100% trust your judgement.
#h5yr 

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by leekelleher** [comment]
Excellent, I'll get a PR together!

I thought it would make sense to have it part of Archetype than a separate library.

**Comment by leekelleher** [comment]
Closing this ticket, opened PR #303
