### ISSUE TITLE
Embedded content 

### ISSUE THREAD

**Issue by qz2rg4** [imulus/Archetype#305]
Have you ever thought to write an embedded content converter ?

In other words archetype will realize it is embedded content and convert it.

https://our.umbraco.org/projects/backoffice-extensions/embedded-content/

**Comment by kgiszewski** [comment]
Perhaps you can explain further.

There are already a few mappers to be used in conjunction with Archetype along with the ability to automatically render it's template.

**Comment by qz2rg4** [comment]
Hi Kevin 

Thanks for getting back to me.

Please can you send me your email so we can discuss this further privately.

**Comment by kgiszewski** [comment]
Sure,

kevin at giszewski.com

Cheers,

Kevin
