### ISSUE TITLE
Version number exposed in CSS/JS/HTML

### ISSUE THREAD

**Issue by leekelleher** [imulus/Archetype#307]
Upgrading to v1.12, I noticed that the CSS/JS and HTML files are stamped with the version number.

The issue with this is that "if" in future we find that a specific version of Archetype has a security flaw, then it is easy for an attacker to discover if a website can be compromised. (Since those assets are publicly exposed)

Obviously I'm not suggesting that Archetype has any security flaws - it's more of a preventative measure.

I raised the same with Umbraco core a while ago... http://issues.umbraco.org/issue/U4-5582
... and GitHub commit comments: https://github.com/umbraco/Umbraco-CMS/commit/4521e31ec528cec03487358821b7ff0fda195887#commitcomment-8363901

:heart: :v: :octocat:

**Comment by kgiszewski** [comment]
Not that I'm entirely disagreeing... :)

But is it just as easy to determine the version of Archetype by simply performing a checksum of the entire `archetype.js` file?

For example:

A script could easily be written to download `archetype.js` from a production server and perform a SHA-1/MD5 hash and bounce it off of known copies on Github/Nuget making the same mapping to versions.

v1.12.0 = D95CD8B070FCEF8667633B7DAA1AEC7E
and so on...

It would merely take a few extra steps but the end result is the same. I'm inclined to go ahead an assume that the version number is always known if desired whether we show it or not.

In fact the argument with Umbraco can also be made. If you perform a checksum of certain core files, you can also easily determine the version.

So in the interest of conceding that is possible, I don't think adding a version number explicitly makes it less secure to someone with malicious intent when weighed against the benefit it may bring.

Ok, your turn ;)

**Comment by leekelleher** [comment]
Touché! :bow: I don't have a counter-argument - you're totally right! :metal:

**Comment by kgiszewski** [comment]
But now you have me scared :) :grimacing:

**Comment by leekelleher** [comment]
It was only that I spotted the version number that it rang alarm bells for me.

To be honest, I don't see Archetype as being a vulnerability - on the other hand, it's a bigger issue for Umbraco.

Let's close this one off as FUD :+1:

**Comment by kgiszewski** [comment]
Indeed :)
