### ISSUE TITLE
NuGet Package for Archetype Binaries

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#312]
See discussion here: https://our.umbraco.org/projects/backoffice-extensions/archetype/sound-off/73913-nuget-for-archetype-binaries

Would be great if, in addition to the current Archetype NuGet package, there were an Archetype.Binaries NuGet package.

**Comment by Nicholas-Westby** [comment]
Just came across another reason to do this: https://github.com/micklaw/Ditto.Resolvers/issues/4#issuecomment-167139494

![comment](https://cloud.githubusercontent.com/assets/5933222/11996802/1176ee50-aa20-11e5-9304-7795232034dc.png)

**Comment by kgiszewski** [comment]
I think I got it separated appropriately, if you get a chance please test it for me.

There are now two packages for Archetype:

https://www.nuget.org/packages/Archetype
https://www.nuget.org/packages/Archetype.Binaries

v1.12.2 is the version that has the split.

**Comment by Nicholas-Westby** [comment]
Nice! Worked well for me. I have asked that this NuGet package be used as a dependency for this other package, which will be the real test: https://github.com/micklaw/Ditto.Resolvers/issues/6

**Comment by kgiszewski** [comment]
:+1:

**Comment by leekelleher** [comment]
Just tried and tested the new NuGet package on the [ditto-labs/Archetype repo](https://github.com/leekelleher/umbraco-ditto-labs/tree/develop/src/Our.Umbraco.Ditto.Archetype), all good! :100: :+1:

**Comment by kgiszewski** [comment]
@leekelleher Super!

**Comment by micklaw** [comment]
All good with this resolvers project too, good work dude!

**Comment by kgiszewski** [comment]
:+1: Thanks :)
