### ISSUE TITLE
Make labels focus input fields

### ISSUE THREAD

**Issue by bjarnef** [imulus/Archetype#313]
I think clicking the labels should focus the input fields. I believe it is a common UX feature (or best practice) when working with forms. Umbraco core does it too.

The labels should have the ```for```attribute which value is the id of the input field.
I have a property "First Name" which has ```for="archetype-property-test-0-0"``` .. but the input has ```id="archetype-property-test-f0-firstName-p0"```

Tested with Archetype 1.12.1
The value of ```for``` and ```id```should match each other.

Furthermore, maybe also display a tooltip for the label with the property alias as it was added in the recent versions of Umbraco using ```ng-attr-title="{{propertyAlias}}"``` (I think it only is added for admin users?)

**Comment by kgiszewski** [comment]
@bjarnef Thanks for the report, maybe the `id` and `for` mismatch is just an oversight.

The property alias would be a nice touch as well. I don't suppose you want to send a PR for this? ;)

**Comment by bjarnef** [comment]
Maybe I can find some time for it. I am not sure if the id is used for something else.. otherwise it should be safe just changing value of ```for``` to match ```id``` value.

For the property alias tooltip it seems to be this part:
https://github.com/umbraco/Umbraco-CMS/blob/e6773dafc1387ae205a9a2d9e5d31bee30a38bfe/src/Umbraco.Web.UI.Client/src/views/directives/umb-property.html#L8
