### ISSUE TITLE
Courier NuGet has older binary (1.7.3)

### ISSUE THREAD

**Issue by leekelleher** [imulus/Archetype#319]
Hi @kgiszewski 

With the new [Archetype.Courier NuGet package, (v1.12.2)](https://www.nuget.org/packages/Archetype.Courier/1.12.2), I've noticed that the actual binary is an older version - the assembly version is set as **1.7.3**.

If you download the NuGet package, extract the DLL, right-click view Properties, you'll see it.

This got me confused, as I couldn't figure out where the "1.7.3" version number would come from.  It took me a while, but I think I've figured it.

The Gruntfile.js tries to get the binary from the /bin/release/ folder, (see line [158](https://github.com/imulus/Archetype/blob/master/Gruntfile.js#L158)), but on line [311](https://github.com/imulus/Archetype/blob/master/Gruntfile.js#L311), the VS projects are being build against "Debug" configuration.  Meaning that only the /bin/Debug/ folder is being updated, and the /bin/Release/ folder would contain whatever was in there previously.

My assumption is that when you last built the Courier resolver (on your machine), it was v1.7.3 - so that's the version that was copied into the NuGet package.

I hope I'm right in thinking this? (otherwise I'm very confused) :wink: 

To resolve this, I'd suggest swapping the msbuild "Debug" configuration with "Release" and update the various paths accordingly.  (I can submit a PR if you want?)

Thanks, Lee

**Comment by kgiszewski** [comment]
@leekelleher confirmed, merged your PR. I went with version `1.12.2.1` and had to manually depend it on `1.12.2` for the main dll.

https://www.nuget.org/packages/Archetype.Courier/1.12.2.1

It *should* work :)

**Comment by kgiszewski** [comment]
Oh and thanks!

**Comment by leekelleher** [comment]
Thanks! :+1: 

No worries. It was a headscratching moment for me - figuring out how it could have happened. :confused:
All good now! :smiley:

**Comment by Nicholas-Westby** [comment]
FYI, if I understand this correctly, this was basically a problem of using either "debug" or "release" and one part was expecting one whereas another part of the code (or process) was expecting the other.

To avoid this problem in one of my projects, I did this: https://github.com/rhythmagency/formulate/blob/442b9dd86f4bcbbfcede225ae22c55c9736dc2d7/src/gruntfile.js#L29

Essentially, that's just looking in the "debug" and "release" folders for the newest files, then using that folder (i.e., it will use the build output that is the most recent). Just thought I'd mention that in case it's useful for your build scenario :-)
