### ISSUE TITLE
Sorting not working for specific instance

### ISSUE THREAD

**Issue by kipusoep** [imulus/Archetype#322]
Hi guys,

I'm using Archetype heavily in a project and it's working great!
Though one of the Archetype data types I created doesn't seem to be able to sort.
When I click and hold the drag icon and drag the item downwards, no ui sort placeholder is visible at all (the light-blue placeholder).
In dev tools I can see the height of the placeholder is 0px, so this is either the issue or the result of the issue.

My Archetype config:
```javascript
{
  "showAdvancedOptions": false,
  "startWithAddButton": false,
  "hideFieldsetToolbar": false,
  "enableMultipleFieldsets": false,
  "hideFieldsetControls": false,
  "hidePropertyLabel": false,
  "maxFieldsets": null,
  "enableCollapsing": true,
  "enableCloning": false,
  "enableDisabling": true,
  "enableDeepDatatypeRequests": false,
  "fieldsets": [
    {
      "alias": "bewonerspanels",
      "remove": false,
      "collapse": false,
      "labelTemplate": "{{title}}",
      "icon": "",
      "label": "Bewonerspanels",
      "properties": [
        {
          "alias": "title",
          "remove": false,
          "collapse": true,
          "label": "Titel",
          "helpText": "De titel van de bewonerspanel. Deze moet overeenkomen met de naam van de groep in MailChimp!",
          "dataTypeGuid": "0cc0eba1-9960-42c9-bf9b-60e150b429ae",
          "value": "",
          "aliasIsDirty": true,
          "required": true
        },
        {
          "alias": "picture",
          "remove": false,
          "collapse": true,
          "label": "Afbeelding",
          "helpText": "De afbeelding van de bewonerspanel",
          "dataTypeGuid": "93929b9a-93a2-4e2a-b239-d99334440a59",
          "value": "",
          "required": true,
          "aliasIsDirty": true
        },
        {
          "alias": "text",
          "remove": false,
          "collapse": true,
          "label": "Tekst",
          "helpText": "De tekst van de bewonerspanel",
          "dataTypeGuid": "ca90c950-0aff-4e72-b976-a30b1ac57dad",
          "value": "",
          "aliasIsDirty": true
        }
      ],
      "group": null,
      "aliasIsDirty": true
    }
  ],
  "fieldsetGroups": [
    
  ],
  "selection": [
    
  ],
  "developerMode": false
}
```

**Comment by kgiszewski** [comment]
@kipusoep Thanks for the info. I can replicate it on 7.2.8. Scratching my head now.

**Comment by kipusoep** [comment]
Great to hear you can replicate this. I did some investigation too but really couldn't find the issue at all :-/

**Comment by kgiszewski** [comment]
Well, here's what I know. If I change your alias from `bewonerspanels` to `bewoner`, it suddenly works.

Here's the issue with renaming. Archetype doesn't handle alias renaming well. If you rename an alias, you lose saved data. So if you can re-enter data easily, I'd recommend that.

If you can't easily reenter the data, you may have to edit your Archetype JSON after you save your configuration but before you save a piece of content. If it's tons of nodes, you might need to loop with the IContent API's or edit via SQL. Backup the DB either way if you go this route.

Now back to the 'why' is this happening. I have no idea. I'd assume it has something to do with a conflict in the sortable directive.

Let me know if you need assistance with anything and I'll get back to you ASAP.

I'm hoping this is just an odd edge case :pray:.

**Comment by kipusoep** [comment]
Wow, just wow... That's really really odd!
I'll be able to edit that instance's data, no prob, but I'm really curious about what the issue with that name is...
Thanks for your help and time, really appreciate it!

**Comment by kgiszewski** [comment]
No problem. I probably won't try to track down the reason just yet as it sounds like it could be a rabbit hole :rabbit: with the core. We can leave this issue here in case anyone can assist or has a similar issue.

**Comment by kipusoep** [comment]
Sure, I just hope nobody else will bump into this and will be unable to find this issue :-)

**Comment by kipusoep** [comment]
Is this a confirmed umbraco core bug?

**Comment by kgiszewski** [comment]
Nope, not confirmed but also very time intensive to track down. Closing for now until we find out anything otherwise.
