### ISSUE TITLE
Add CTH.ExtendedMediaPicker

### ISSUE THREAD

**Issue by kipusoep** [imulus/Archetype#328]
Could you guys add the 'CTH.ExtendedMediaPicker' to the 'getNativeLabel' method, like this?

```js
function getNativeLabel(datatype, value, scope) {

    switch (datatype.selectedEditor) {
    	case "Imulus.UrlPicker":
    		return imulusUrlPicker(value, scope, {});
    	case "Umbraco.TinyMCEv3":
    		return coreTinyMce(value, scope, {});
        case "Umbraco.MultiNodeTreePicker":
            return coreMntp(value, scope, datatype);
    	case "Umbraco.MediaPicker":
    	case "CTH.ExtendedMediaPicker":
            return coreMediaPicker(value, scope, datatype);
        case "Umbraco.DropDown":
            return coreDropdown(value, scope, datatype);
    	default:
    		return "";
    }
}
```

**Comment by kgiszewski** [comment]
@kipusoep, we can likely do this. Can you point me to what package belongs to `CTH.ExtendedMediaPicker`?

Also, if you send me a PR, this can happen pretty fast.

**Comment by kipusoep** [comment]
It is an extended media picker with direct edit link, but since Umbraco 7.4 already includes an improved Media Picker, it's not necessary anymore.

**Comment by kgiszewski** [comment]
Cool no worries, if you stumble upon any other datatypes that need included let us know.
