### ISSUE TITLE
IsFirst(), IsLast() and other Id-dependant IPublishedContent extension methods not working

### ISSUE THREAD

**Issue by arknu** [imulus/Archetype#329]
I was iterating though an Archetype transformed to IPublishedContent using ToPublishedContentSet() (great feature, BTW). I tried to use the IsFirst() extension method, but that did not work work.

A little research reveals that ArchetypePublishedContent simply returns default(int) for the Index and Id properties. This seems rather strange. Wouldn't a better option be to just assign a sequential Id (so the first item is 1, the next 2 etc.)?

**Comment by kgiszewski** [comment]
@arknu I think the index would make sense sequentially but I'm not sure that the Id being populated with anything makes sense. 

@leekelleher added this functionality, perhaps it'd be good to get his input.

**Comment by leekelleher** [comment]
Populating the `Index` makes sense, and should be easy to do (for `ToPublishedContentSet()` calls).

I'm not sure about the `Id` though, it would open a can-of-worms (about node retrieval via ID), which we experienced on Nested Content.

I'll take a look at populating the `Index` this week... unless anyone wants to submit a PR before I do? ;-)

**Comment by arknu** [comment]
@leekelleher Populating the Index property would be enough, I guess, to make these methods work. So that should fix this issue. I agree that ID could be potentially problematic, so that is probably best left alone.

**Comment by leekelleher** [comment]
I've opened a PR for this, #330

Unfortunately extension methods like `Siblings()` (or `FollowingSibling()`, `PrecedingSibling()`) wont work, due to Umbraco's internal calls to `.Parent.Children`.
