### ISSUE TITLE
RTE isn't working properly

### ISSUE THREAD

**Issue by tomfulton** [imulus/Archetype#33]
- [ ] When adding multiple rows, the subsequent rows are missing the WYSIWYG (only shows the toolbar).
- [ ] When adding a new row and returning to the first row, the WYSIWYG area is very long (1000px+)

**Comment by navid-dada** [comment]
I have same issue: "formats list is empty" and i try [this](https://github.com/kgiszewski/Archetype/issues/33#issuecomment-39017250) solution but this odes not work for me :(

**Comment by Nicholas-Westby** [comment]
@navid-dada This issue is several years old, and so is not likely the same exact issue you are experiencing. I recommend opening a new issue with all the relevant details (steps to reproduce, screenshots, Umbraco & Archetype versions, etc.).
