### ISSUE TITLE
Archetype overwrites styles for property editors in fieldsets

### ISSUE THREAD

**Issue by bjarnef** [imulus/Archetype#337]
It seems Archetype overwrites styles for property editors in fieldsets, e.g. in Umbraco 7.4.x the Media Picker has edit and delete buttons, where Archetype overwrites the font color.

![image](https://cloud.githubusercontent.com/assets/2919859/13495795/0106ec28-e14d-11e5-886f-e9049680cfdc.png)

It should look like this:

![image](https://cloud.githubusercontent.com/assets/2919859/13495817/1de07b98-e14d-11e5-9416-3cd3b466b75d.png)

Instead of using this in css:
```
.archetypeEditor .icon
```

it can be changed to:

```
.archetypeEditor > .icon
```

or something like that to avoid styling deep level elements.

Furthermore I think it would be better to use the default "darker grey" color for the actions instead of the "lighter grey" color as the buttons look like they are disabled.

![image](https://cloud.githubusercontent.com/assets/2919859/13495965/f08bc944-e14d-11e5-8b67-4ea5780bd91c.png)

For my changes to Url Picker I have something similar, take a look: 
http://dev.bjarnefyrstenborg.dk/url-picker-dist.zip

**Comment by kjac** [comment]
@bjarnef Thanks for reporting this. I've submitted a fix.

The icons will keep their disabled look for now. Work is underway to actively use this to display enabled/disabled/published/unpublished state :)

**Comment by kgiszewski** [comment]
Fixed by #348
