### ISSUE TITLE
Brainstorm: "2500 limit" issue

### ISSUE THREAD

**Issue by tomfulton** [imulus/Archetype#34]
We're storing the configuration of each Archetype in the `cmsDataTypePrevalues` table, but the field is an `nvarchar(2500)`.  This causes a YSOD to bubble up on Save if your Archetype's configuration (JSON blob) ends up being longer than that.

Since we've removed some of the config options, this issue probably isn't *as* prevalent, but it still happens on some of my test datatypes.

The current workaround is to change the limit in SQL:
`ALTER TABLE [your-db] ALTER COLUMN [value] nvarchar(MAX)`

There's probably not much we can do to *fix* this, but maybe we can ease the pain somehow so users don't see a YSOD and help guide them towards the solution.

**Comment by owlyowl** [comment]
Hi guys we're getting this behaviour.. we're running 7.2

https://our.umbraco.org/forum/developers/extending-umbraco/66856-custom-property-editor-with-angular-array-to-add-rows-throwing-500-on-save-and-publish

Just wondering if this is the same issue. We're getting an SQL truncated exception

**Comment by kjac** [comment]
Issue solved on our. @owlyowl please don't post non-Archetype related questions here :)
@kgiszewski this issue should probably be closed as it's been fixed in the core since 7.2?

**Comment by kgiszewski** [comment]
This is now fixed with 7.2.x :)
