### ISSUE TITLE
Config Model No Longer Works

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#342]
Archetype 1.12.3. Umbraco 7.4.1 and Umbraco 7.4.2.

In short, pasting a config model from one Archetype to another no longer updates the destination Archetype to have the same configuration as the source Archetype:

![config](https://cloud.githubusercontent.com/assets/5933222/14127561/b8fa2cfc-f5cd-11e5-8c86-31db8435124d.png)

My suspicion is that this is related to that recent change in which Archetype was modified so that the dialogs are no longer based on the model used by the primary screen. Or maybe it was the reverse. Can't remember exactly.

**Comment by kgiszewski** [comment]
Hmmm, indeed. Maybe that's why I chose the previous way of doing it. Whelp, guess I need to fix that.

**Comment by kjac** [comment]
I've submitted PR #350 to fix this :)

**Comment by kgiszewski** [comment]
Ace!

**Comment by kgiszewski** [comment]
Fixed by #350
