### ISSUE TITLE
Cannot delete items/properties!

### ISSUE THREAD

**Issue by hyrmedia** [imulus/Archetype#346]
Clicking the "X" icon to delete an item does not work for me.

When either creating/modifying an Archetype data type, I can add new properties or modify existing ones; but clicking the "X" on a property does not delete the property.

In the Content area, when viewing a list of items managed by an Archetype-based property editor, clicking the "X" icon does not delete does not delete the item.

In fact, clicking the "X" in either of these cases does absolutely nothing -- it doesn't even generate a JS error in the console. Everything else still works -- adding items/properties, modifying existing properties and so on -- I just can't delete anything.

This is a big problem; as a content editor there's just no way to delete an item, and as a developer, I could delete and re-add the entire property, but then they'd have to add all the original content again.

![umbraco-archetype-delete-bug-20160330](https://cloud.githubusercontent.com/assets/2054138/14153573/920a3e18-f675-11e5-9717-be7e7073261d.jpg)

**Comment by Nicholas-Westby** [comment]
Which version of Archetype are you on? I'm on 1.12.3 (currently, the latest) with Umbraco 7.4.1 and I don't have this issue.

**Comment by kjac** [comment]
I can't reproduce this either, tested on both 7.3 and 7.4

**Comment by kgiszewski** [comment]
I can't reproduce either. Please provide some steps to reproduce. Is it possible that another package might have conflicting styles? We can reopen if more details can be provided.

**Comment by iTanyusha** [comment]
I've had exactly the same issue and in my case it turned out to be because Google Chrome decided not to show confirm window until it's been updated to the last version, and that's what used to confirm in removeRow function in App_Plugins\Archetype\js\archetype.js
