### ISSUE TITLE
Breaking JSON Archetype if using SerializeForPersistence before JsonConvert.SerializeObject

### ISSUE THREAD

**Issue by biapar** [imulus/Archetype#349]
Hi,

if using SerializeForPersistence before  JsonConvert.SerializeObject, the JSON Archetype data break.
Why?

```
archetypePoll.Fieldsets = currentFieldsets;

 //var jsonDomande = archetypePoll.SerializeForPersistence();

questionPoll.SetValue("domanda", JsonConvert.SerializeObject(archetypePoll));
```

**Comment by kgiszewski** [comment]
Just use `SerializeForPersistence` and that will return a value to save.

**Comment by kgiszewski** [comment]
Closing for now. If there is a specific bug to report, we can revisit this.

**Comment by biapar** [comment]
How to save?
If I use this, it works questionPoll.SetValue("domanda", JsonConvert.SerializeObject(archetypePoll)); without call SerializeForPersistence
