### ISSUE TITLE
Tags Duplicate When Selected in Archetype Fieldset

### ISSUE THREAD

**Issue by Nicholas-Westby** [imulus/Archetype#353]
When I type "General" and click "General" from the autosuggest list of tags, I see this:

![tags](https://cloud.githubusercontent.com/assets/5933222/14400950/a6a10882-fdb6-11e5-9553-0bfa9104b872.png)

It adds the "General" tag as well as the text "General" after that tag. I do no see this with other tag properties that are on the document type rather than inside of an Archetype fieldset.

I also see an error in my JavaScript console when I select a tag from the autosuggest list:
![error](https://cloud.githubusercontent.com/assets/5933222/14400989/7e5b1a7e-fdb7-11e5-9354-35ec18ac0042.png)

Some info:
* Archetype 1.12.3.
* Umbraco 7.4.1.
* JSON storage configured for the tags.
* OS X
* Chrome

Here is my tags data type:
![type](https://cloud.githubusercontent.com/assets/5933222/14400968/073835f8-fdb7-11e5-96a1-747251658236.png)

**Comment by kgiszewski** [comment]
@Nicholas-Westby this is also fixed in #345 as far as I can tell. Without the PR, this was doing the same for me.

**Comment by Nicholas-Westby** [comment]
Awesome!
