### ISSUE TITLE
CDATA tags in property field in Archetype model breaks view

### ISSUE THREAD

**Issue by idontbyte** [imulus/Archetype#357]
Archetype property (e.g. text area) with CDATA in it's value seems to break the rendering of the view, Html.RenderArchetypePartials does not return anything.

e.g.
```
    /* <![CDATA[ */
    /* ]]> */
```

**Comment by kgiszewski** [comment]
Hmm, I can confirm this does happen. I'm looking to see if anything obvious jumps out to me.

**Comment by kgiszewski** [comment]
Do you know if it is isolated to using `@Html.RenderArchetypePartials`? i.e. does it work if you use it without

**Comment by idontbyte** [comment]
Seems to be a wider Umbraco problem - due to the way the cache is held in XML, specifically in CDATA fields you can't have a CDATA in a CDATA. In order to work around this I stored the data in an Umbraco property (instead of Archetype) and then on the front end I did a check for the property hasValue and if it does I access from the database - not the best solution but it works and it won't have a great performance impact on my site. Don't think it's the responsibility of Archetype to get this working so I'll close!

**Comment by kgiszewski** [comment]
👍  Thanks for the detective work :)
