### ISSUE TITLE
Sorting breaks whenever I place an RTE anywhere within same DocType

### ISSUE THREAD

**Issue by KooblaKabla** [imulus/Archetype#366]
Hi,

I understand that there are several issues mentioned already that are similar to this one (e.g. [#282](https://github.com/imulus/Archetype/issues/282), [#322](https://github.com/imulus/Archetype/issues/322)), however I have it happen whenever I have a Rich Text Editor datatype as part of the same Document Type. So, the RTE is not part of my Archetype datatype, it just happens to be in the same Document Type (not even on the same tab).

To put it another way, to get sorting fieldsets working again I don't need to change my Archetype datatype at all, all I have to do is remove any RTE datatypes from my doctype.

![archetype-sort-bug-1](https://cloud.githubusercontent.com/assets/19681202/15700972/e62826c0-2809-11e6-99ff-de1609f8f525.jpg)

![archetype-sort-bug-2](https://cloud.githubusercontent.com/assets/19681202/15700985/f7cce3f2-2809-11e6-9080-4743a4ef8363.jpg)

![archetype-sort-bug-3](https://cloud.githubusercontent.com/assets/19681202/15700988/fdcae86c-2809-11e6-908c-452395ff0f66.jpg)

I am using Umbraco 7.4.3 and Archetype 1.13

I have tried renaming my archetype alias (as per [#322](https://github.com/imulus/Archetype/issues/322)) however that did not fix the problem.

I have also updated underscore.js to the latest version (as per [#282](https://github.com/imulus/Archetype/issues/282)) to see whether that would work, but alas it did not. (Although the error message I get isn't the same as #282 either).

Just to clarify even further, I am using several (different and the same) archetype datatypes throughout the project. All Archetype sorting works fine on pages that use doctypes containing no RTE datatypes.

Any Ideas?

**Comment by Nicholas-Westby** [comment]
Here's a workaround: https://github.com/imulus/Archetype/pull/364

**Comment by KooblaKabla** [comment]
Thanks Nicholas. Got it working.

**Comment by kipusoep** [comment]
Thanks for the work-around!
