### ISSUE TITLE
Unable to sort archetype items.

### ISSUE THREAD

**Issue by jacqueswho** [imulus/Archetype#371]
Umbraco version 7.4.3
Archetype version 1.13.0

Unable to sort items. When you begin dragging the item it highlights the whole thing and the icon stays on a move icon.

https://gyazo.com/1cff329a4d8998f2606ba6a6b18586fe

**Comment by kgiszewski** [comment]
@jacqueswho this is likely fixed here: https://github.com/imulus/Archetype/pull/364 which should be in the next release.

**Comment by jacqueswho** [comment]
I did look at [#364 ](url) but my archetype has no rte but does have a 
https://our.umbraco.org/projects/backoffice-extensions/multi-url-picker/

**Comment by GertyEngrie** [comment]
:+1:  When would the next release be due approx? :-)

**Comment by kgiszewski** [comment]
@GertyEngrie today

**Comment by GertyEngrie** [comment]
Thanks!

**Comment by jacqueswho** [comment]
Thank you. fix worked
